language: scala
scala:
   - 2.11.8
   - 2.12.1
jdk:
  - oraclejdk8
script:
  - "sbt ++$TRAVIS_SCALA_VERSION test"
branches:
  except:
    - /^v[0-9]/
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2